import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import LightBulb from '../../public/images/profile/mern.png'
import TransitionEffect from '@/components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>Kamrul Saad | Portfolio</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <TransitionEffect />
      <main className='text-dark flex items-center w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex lg:flex-col items-center justify-between w-full'>
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt='Kamrul Saad' className="w-full h-auto lg:hidden md:inline-block md:w-full" priority
                sizes='(max-width: 768px) 100vw, 
              (max-width: 1200px) 50vw, 50vw'
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText className='!text-6xl !text-left 
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
              ' text="Unleashing Innovation Through Code and Design"></AnimatedText>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>Experienced and energetic web developer with over one year of experience
                effectively managing web development projects from conception to completion.
                Using digital platforms to increase overall company productivity.</p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href='/dummy.pdf'
                  target='_blank'
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold  hover:bg-light hover:text-dark transition duration-300 ease-in-out mr-4 border-solid border-trasparent border-2 hover:border-dark dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base'
                  download={true}
                >Resume
                  <LinkArrow className={'h-6 w-6 ml-2'} />
                </Link>
                <Link href='mailto:skamrul2680@gmail.com'
                  target='_blank'
                  className='ml-4 text-lg font-medium capitalize text-dark hover:underline dark:text-light md:text-base'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <div className='absolute right-8 bottom-8 inline-block w-60 md:hidden'>
          <Image src={LightBulb} alt='Kamrul Saad' className="w-full h-auto" />
        </div>
      </main>
    </>
  )
}
